version: '3.6'

services:
  # API
  api:
    image: docker.pkg.github.com/landazuripaul/codenames/codenames-api:latest
    volumes:
      - ./packages/api/env/production.env:/usr/src/codenames/packages/api/env/production.env
    expose:
      - '4000'
    environment:
      - NODE_ENV=production

  # Frontend
  frontend:
    image: docker.pkg.github.com/landazuripaul/codenames/codenames-frontend:latest
