version: '3.6'

services:
  # API
  api:
    image: docker.pkg.github.com/landazuripaul/codenames/codenames-api:0.1.0
    volumes:
      - ./packages/api/env/production.env:/usr/src/codenames/packages/api/env/production.env
    expose:
      - '4000'
    environment:
      - NODE_ENV=production

  # Frontend
  frontend:
    image: nginx:stable
    volumes:
      - ./packages/frontend/www/:/usr/share/nginx/html:ro
      - ./packages/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
